name: Deploy backend

#on:
#  push:
#    branches:
#      - main
#    paths: 
#      - 'backend/**'
on:
  workflow_dispatch:
jobs:

  DeploymentBackend:

    runs-on: ubuntu-latest
    
    steps:
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
      - 
        uses: actions/checkout@v3
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          context: ./backend
#          tags: eugeneparkhom/pomodoro_backend:1.0.${{ github.run_number }}
      - name: Initialize and update submodule
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          git submodule update --init --recursive
          
      - name: Switch to host_settings branch
        run: cd ./host_settings
      - run: git branch -a
      
      - run: git status
      
      - name: Modify host_settings/run_backend_docker_container.sh
        run: |
            # Replace the static tag version in script.sh with the run number
            sed -i "s/1.0.0/${${{ github.run_number }}}/" ./scripts/run_backend_docker_container.sh
      
      - name: Commit and push changes
        run: |
          # modify files
          git add .
          git commit -m "modify host_settings files"
          git push origin host_settings
