name: Deploy backend

#on:
#  push:
#    branches:
#      - main
#    paths: 
#      - 'backend/**'
on:
  workflow_dispatch:
jobs:

  DeploymentBackend:

    runs-on: ubuntu-latest
    
    steps:
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
      - 
        uses: actions/checkout@v3
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          context: ./backend
#          tags: eugeneparkhom/pomodoro_backend:1.0.${{ github.run_number }}

      - name: Go to host_settings folder and Modify host_settings/run_backend_docker_container.sh
        run: |

          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"

          git status
          git branch -a

          git submodule update --init --recursive
          cd host_settings/

          git checkout host_settings
          
          git status
          git branch -a

          sed -i "s/pomodoro_backend:\([0-9]\+\.[0-9]\+\.[0-9]\+\)/pomodoro_backend:1.0.${{ github.run_number }}/" scripts/run_backend_docker_container.sh

          echo 'git add'
          git add scripts/run_backend_docker_container.sh
          ech 'git commit'
          git commit -m "modify host_settings files"

          echo 'git config'
          git config --list
          
          echo 'git push'
          git push 

