name: Deploy pipeline

on:
  push:
    branches: ["main"]
    paths:
      - '**.js'
      - '**.html'
      - 'public/**'
      - 'src/**'
      - 'Dockerfile'
  
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - 
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - 
        name: Install pre-production dependencies
        run: npm install --production
      - 
        name: Build (minification)
        run: npm run build
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -       
        name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: pomo_test
      -
        name: Test Docker image
        run: |
          docker run --rm -d -p 8080:80 pomo_test
          apt-get install -y curl
          chmod +x /test/dockerImageTest.py
          ./test/dockerImageTest.py

      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: eugeneparkhom/pomodoro:latest