name: Deploy pipeline

on:
  push:
    branches: ["main"]
    paths:
      - '**.js'
      - '**.html'
      - 'public/**'
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/*.yml'
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - 
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - 
        name: Install pre-production dependencies
        run: npm install --only=production
      - 
        name: Build (minification)
        run: npm run build
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: pomo_test
      -
        name: Test
        run: |
          docker run --rm pomo_test
          sudo apt-get install -y curl
          chmod +x /test/dockerImageTest.py
          ./test/dockerImageTest.py
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: eugeneparkhom/pomodoro:latest
