name: Deploy backend

#on:
#  push:
#    branches:
#      - main
#    paths: 
#      - ./backend
on: 
  workflow_dispatch:   

jobs:

  DeploymentBackend:

    runs-on: ubuntu-latest
    
    steps:
      #-
      #  name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3
      - 
        uses: actions/checkout@v3
      #-
      #  name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3
      #-
      #  name: Login to Docker Hub
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      #-
      #  name: Build and push
      #  uses: docker/build-push-action@v5
      #  with:
      #    push: true
      #    context: ./backend
      #    tags: eugeneparkhom/pomodoro_backend:1.0.${{ github.run_number }}
      - 
        name: Modify host_settings/run_backend_docker_container.sh
        run: |
            # Get the current run number from GitHub Actions
            RUN_NUMBER=${{ github.run_number }}
  
            # Replace the static tag version in script.sh with the run number
            sed -i "s/1.0.0/${RUN_NUMBER}/" scripts/run_backend_docker_container.sh
        working-directory: ./host_settings

      - name: Commit and push changes
        run: |
          # modify files
          git add .
          git commit -m "modify host_settings files"
          cd .. # back to pomodoro_timer folder
          git add host_settings
          git commit -m "record host_settings new SHA1"
          git push
        working-directory: ./host_settings