name: Deploy frontend

on:
  push:
    branches:
      - main
    paths: 
      - 'frontend/**'

jobs:

  DeploymentFrontend:

    runs-on: ubuntu-latest
    
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        uses: actions/checkout@v3
      - 
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - 
        name: Install pre-production dependencies
        run: npm install --omit=dev
        working-directory: ./frontend
      - 
        name: Get code from host_settings submodule
        run: |
          git submodule init
          git submodule update
      - 
        name: Build (minification)
        run: make build
        working-directory: ./frontend
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./frontend
          tags: eugeneparkhom/pomodoro_frontend:1.0.${{ github.run_number }}
