name: Deploy backend

#on:
#  push:
#    branches:
#      - main
#    paths: 
#      - 'backend/**'
on:
  workflow_dispatch:
jobs:

  DeploymentBackend:

    runs-on: ubuntu-latest
    
    steps:
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
      - 
        uses: actions/checkout@v3
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          context: ./backend
#          tags: eugeneparkhom/pomodoro_backend:1.0.${{ github.run_number }}
      - name: Initialize and update submodule
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          git submodule update --init --recursive
          
      - name: Go to host_settings folder 
        run: cd ./host_settings
      
      - name: Fetch branches from origin
        run: git fetch --all

      - name: Create temorarily branch
        run: git checkout -b temp_branch

      - name: Pull from origin host_settings bransh to temp_branch
        run: git pull origin host_settings
        
      - name: Modify host_settings/run_backend_docker_container.sh
        run: |
            # Replace the static tag version in script.sh with the run number
            sed -i "s/pomodoro_backend:\([0-9]\+\.[0-9]\+\.[0-9]\+\)/pomodoro_backend:1.0.${{ github.run_number }}/" ./scripts/run_backend_docker_container.sh
      
      - name: Commit changes
        run: |
          # modify files
          git add ./scripts/run_backend_docker_container.sh
          git commit -m "modify host_settings files"
             
      - name: Push changes
        run: git push origin temp_branch:host_settings