name: Push to main

on:
  push:
    branches: ["main"]
    paths:
      - '**.js'
      - '**.html'
      - 'public/**'
      - 'src/**'
      - 'Dockerfile'

jobs:
  Test_by_pushin_to_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for Merge Push
        run: |
          # Get the commit message of the latest commit in the push
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          
          # Check if the commit message contains "[skip test]"
          if [[ $COMMIT_MESSAGE == *"[skip test]"* ]]; then
              echo "Skipping testWorkflow."
              exit 78 # Exit with a neutral status code to skip the workflow
          fi
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Run linter for JS and HTML
        run: npm run lint
      - name: Setup Geckodriver
        uses: browser-actions/setup-geckodriver@latest
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
      - name: Run local http server
        run: npm run run_server &
      - name: Run test suite
        run: npm run test
      - name: Kill local http server
        run: pkill -f http-server
      - name: TruffleHog Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          # Repository path
          path: ./
          # Start scanning from here (usually main branch).
          base: ${{ github.event.repository.default_branch }}
          extra_args: --debug --only-verified
