name: Pomodoro app test suite

on:
  push:
    branches: [ "dev" ]

jobs:
  TestSuiteAndMerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Run linter for JS and HTML
        run: npm run lint
      - name: Setup Geckodriver
        uses: browser-actions/setup-geckodriver@latest
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
      - name: Run local http server
        run: npm run run_server &
      - name: Run test suite
        run: npm run test
      - name: Kill local http server
        run: pkill -f http-server
      - name: TruffleHog Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          # Repository path
          path: ./
          # Start scanning from here (usually main branch).
          base: ${{ github.event.repository.default_branch }}
          extra_args: --debug --only-verified
      - name: Merge to main (if tests pass)
        if: success() && github.ref == 'refs/heads/dev'
        run: |
          git checkout main
          git merge --squash dev
          git commit -m "Pomodoro v0.0.${{ github.run_number }}"
          git push origin main