name: Pomodoro app test suite

on:
  pull_request:
    types: ["opened"]
    branches: [ "main" ]

jobs:
  TestFrontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'


      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run linter for JS and HTML
        run: npm run lint
        working-directory: ./frontend
      - name: Setup Geckodriver
        uses: browser-actions/setup-geckodriver@latest
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
      - name: Run test suite
        run: npm run test
        working-directory: ./frontend
      - name: Kill local http server
        run: pkill -f http-server
      - name: TruffleHog Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          # Repository path
          path: ./
          # Start scanning from here (usually main branch).
          base: ${{ github.event.repository.default_branch }}
          extra_args: --debug --only-verified
  TestBackend:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: 'test_key'
      FERNET_KEY: 'yLPvzO2L59Q6znzC1G0gudb5xyfP1CJCuQmcfy18La8='
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Poetry
        run: |
            curl -sSL https://install.python-poetry.org | python3 -
            source $HOME/.poetry/env
      - name: Install dependencies
        run: ~/.local/bin/poetry install --no-root
        working-directory: ./backend/pomodoro_server
      - name: Run test suite
        run: make test
        working-directory: ./backend/pomodoro_server